- name: test
  hosts: localhost
  tasks:
    - name: patch
      debug:
        msg: "testing if playbook works on awx"

    - name: check date
      debug:
        msg: "{{ ansible_date_time.date }}"

    - shell: printf "X\nY\nZ\n   1 some_word1\n   1 some_word2\n   1 some_word3\n   1 some_word4" |  awk '{print $2}'
      register: output
    - debug:
        msg: "{{ output.stdout_lines }}"

    - name: Save command output for later
      set_fact:
        cacheable: yes
        output1: "{{ output.stdout_lines }}"


    - name: Generate report
      hosts: localhost
      delegate_facts: True
      run_once: yes
      template:
        src: ./test.j2
        dest: "./test.txt"

    # - name: Save command output for later
    #   set_fact:
    #     cacheable: yes
    #     output: "{{ msg }}"
