- name: test
  hosts: 20.222.86.158
  tasks:
    - name: patch
      debug:
        msg: "testing if playbook works on awx"

    - name: check date
      debug:
        msg: "{{ ansible_date_time.date }}"

    - shell: printf "X\nY\nZ\n   1 some_word1\n   1 some_word2\n   1 some_word3\n   1 some_word4" |  awk '{print $2}'
      register: output
    - debug:
        msg: "{{ output.stdout_lines }}"

    - name: Save command output for later
      set_stats:
        data:
          output1: "{{ output.stdout_lines[3:] }}"

    # - name: create folder
    #   delegate_facts: True
    #   run_once: yes
    #   file:
    #     path: "./reports"
    #     state: directory

    # - name: Generate report
    #   template:
    #     src: ./test.j2
    #     dest: "./test.csv"

        # - name: Save command output for later
        #   set_fact:
        #     cacheable: yes
        #     output: "{{ msg }}"
