- name: test
  hosts: localhost
  tasks:
    - name: patch
      debug:
        msg: "testing if playbook works on awx"

    - name: Date
      set_fact:
        date: "Date: {{ ansible_date_time.date }}"

    - name: Time
      set_fact:
        time: "Time: {{ ansible_date_time.time }}"

    - name: check date
      debug:
        var: date
  
    - name: check time
      debug:
        var: time


    - shell: printf "X\nY\nZ\n   1 some_word1\n   1 some_word2\n   1 some_word3\n   1 some_word4" |  awk '{print $2}'
      register: output
    - debug:
        msg: "{{ output.stdout_lines }}"

    - name: Save command output for later
      set_stats:
        data:
          output1: "{{ output.stdout_lines[3:] }}"

    - name: get json output
      set_fact: 
        combine_data: "{{ combine_data | default({}) | combine({'date': date, 'time': time}) }}"
        cacheable: yes
    
          

    # - name: create folder
    #   delegate_facts: True
    #   run_once: yes
    #   file:
    #     path: "./reports"
    #     state: directory

    # - name: Generate report
    #   template:
    #     src: ./test.j2
    #     dest: "./test.csv"

        # - name: Save command output for later
        #   set_fact:
        #     cacheable: yes
        #     output: "{{ msg }}"
