- name: test
  hosts: localhost
  tasks:
    - name: patch
      debug:
        msg: "testing if playbook works on awx"


- name: Save command output for later
  set_fact:
    cacheable: yes
    output: "{{ output.stdout_lines }}"
