- name: test
  hosts: localhost
  tasks:
    # - name: create folder
    #   delegate_facts: True
    #   run_once: yes
    #   file:
    #     path: "/c/Users/Khoo Ai Lin/Desktop/Cloud suport and devops/5_Apprenticeship/ansible/awx/test"
    #     state: directory
    # - name: test code version
    #   debug:
    #     msg: code version is " {{ hostvars['localhost']['output1'] }} "

    - name: test code version two
      debug:
        var: output1
    

    
    # - name: create folder
    #   delegate_facts: True
    #   run_once: yes
    #   file:
    #     path: "/var/lib/awx/projects/reports"
    #     state: directory

    - name: Generate report
      template:
        src: ./test.j2
        # dest: "./var/lib/awx/projects/reports/test.txt"
        dest: "/c/Users/Khoo Ai Lin/Desktop/Cloud suport and devops/5_Apprenticeship/ansible/awx/test/test.txt"
    #ansible_python_interpreter: '{{ ansible_playbook_python }}'

